#! /bin/sh
BUILD_DIR=$1
INSTALL_DIR=$2
JNI_CLASS=$3
CMAKE_SOURCE=$4

mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
cmake -DCMAKE_MODULE_PATH="~/.local/share" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DJNI_CLASS_INCLUDE_DIR="$JNI_CLASS" "$CMAKE_SOURCE"
make install